### PR TITLE
Return usage info in getRecordPure

### PR DESCRIPTION
**Pull request by kuznero**
This time properly returning usage information.

### CODE REVIEW

**Comment by Gabriella439** [comment]
Thanks!

**Comment by kuznero** [comment]
Now, I must admit there is more... When you specify "command --help" it does not show you help for command specified. I will still need to figure out how to do so.

**Comment by Gabriella439** [comment]
Since I need to make a release for GHC 8, what I will do for now is just simplify this to just return `Maybe a` (i.e. no usage information) and then we can later release an extended version that gets the usage information correct

**Comment by nkpart** [comment]
It'd be great if you could bring this into the library. Right now when I'm testing CLIs the error message is discarded and it makes things hard to test.

**Pull request merged**
