### PR TITLE
Add Eq to the "helper wrappers" (<?>), (<!>), (<#>)

### PR DESCRIPTION
**Pull request by googleson78**

### CODE REVIEW

**Comment by Gabriella439** [comment]
Thank you for contributing that!

**Comment by googleson78** [comment]
Now I'm wondering post-factum whether we should just add all the easy to derive instances for them, or at least `Ord` so someone could potentially put those in a `Map`, but that sounds like it's getting extremely niche.

**Comment by googleson78** [comment]
Thanks for the awesome library btw! :heart:

**Comment by Gabriella439** [comment]
You're welcome!

**Pull request merged**
